spring.application.name=commit-translator-jp

# H2 Database Settings 
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# This lets us see the DB in the browser later
spring.h2.console.enabled=true

GEMINI_API_KEY=${GEMINI_API_KEY}

gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent